---
- name: Create Consul configuration directory
  file:
    path: /etc/consul.d
    state: directory
    mode: '0755'

- name: Copy Consul configuration file
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  notify: Restart Consul

- name: Create data directory for Consul
  file:
    path: /opt/consul
    state: directory
    mode: '0755'

- name: Create systemd service file for Consul
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Consul