---
- name: Create Consul user
  user:
    name: consul
    home: /opt/consul
    shell: /bin/false

- name: Create Consul group
  group:
    name: consul

- name: Change ownership of Consul data directory
  file:
    path: /opt/consul
    owner: consul
    group: consul
    recurse: yes