---
- name: Setup Consul and Nomad Cluster
  hosts: nomad_consul_servers, nomad_consul_clients
  become: true
  roles:
    - consul
    - docker
    - nomad

  tasks:
    - name: Display Hostname for Debugging
      debug:
        var: inventory_hostname

    - name: Test Connection to Hosts
      ping:
