---
- name: Ensure Nomad is started and enabled
  systemd:
    name: nomad
    state: started
    enabled: yes

- name: Wait for Nomad to start
  pause:
    seconds: 30
    
- name: Gather list of internal server IPs
  set_fact:
    nomad_server_ips: "{{ groups['tst'] | map('extract', hostvars, 'internal_ip') | join(' ') }}"

- name: Join Nomad cluster
  command: "nomad server join {{ nomad_server_ips }}"
  register: join_result

- name: Check Nomad server members
  command: nomad server members
  register: members_result

- name: Check Nomad node status
  command: nomad node status
  register: node_status_result

- name: Print join result
  debug:
    msg: "{{ join_result.stdout }}"

- name: Print Nomad server members
  debug:
    msg: "{{ members_result.stdout }}"

- name: Print Nomad node status
  debug:
    msg: "{{ node_status_result.stdout }}"