---
- include_tasks: download.yml
- include_tasks: bridge-nf.yml
- include_tasks: cni.yml
- include_tasks: config.yml
- include_tasks: manage.yml
- include_tasks: join-cluster.yml
- include_tasks: deploy-nginx.yml