---
- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present

- name: Ensure user {{ srv_service_user }} is added to the docker group
  ansible.builtin.user:
    name: nomad
    groups: docker
    append: yes

- name: Create Docker daemon.json with mirror configuration
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-opts": {
          "max-size": "200m"
      },
        "registry-mirrors": [
          "https://dockerhub.timeweb.cloud",
          "https://dockerhub1.beget.com",
          "https://mirror.gcr.io"
        ]
      }

- name: Ensure Docker is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes